export const CountryList = [
  { symbol: '', name: 'Select country'},
  { symbol: 'AF', name: 'Afghanistan'},
  { symbol: 'AX', name: 'Aland Islands'},
  { symbol: 'AL', name: 'Albania'},
  { symbol: 'DZ', name: 'Algeria'},
  { symbol: 'AS', name: 'American Samoa'},
  { symbol: 'AD', name: 'Andorra'},
  { symbol: 'AO', name: 'Angola'},
  { symbol: 'AI', name: 'Anguilla'},
  { symbol: 'AQ', name: 'Antarctica'},
  { symbol: 'AG', name: 'Antigua'},
  { symbol: 'AR', name: 'Argentina'},
  { symbol: 'AM', name: 'Armenia'},
  { symbol: 'AW', name: 'Aruba'},
  { symbol: 'AU', name: 'Australia'},
  { symbol: 'AT', name: 'Austria'},
  { symbol: 'AZ', name: 'Azerbaijan'},
  { symbol: 'BS', name: 'Bahamas'},
  { symbol: 'BH', name: 'Bahrain'},
  { symbol: 'BD', name: 'Bangladesh'},
  { symbol: 'BB', name: 'Barbados'},
  { symbol: 'BY', name: 'Belarus'},
  { symbol: 'BE', name: 'Belgium'},
  { symbol: 'BZ', name: 'Belize'},
  { symbol: 'BJ', name: 'Benin'},
  { symbol: 'BM', name: 'Bermuda'},
  { symbol: 'BT', name: 'Bhutan'},
  { symbol: 'BO', name: 'Bolivia'},
  { symbol: 'BQ', name: 'Bonaire'},
  { symbol: 'BA', name: 'Bosnia and Herzegovina'},
  { symbol: 'BW', name: 'Botswana'},
  { symbol: 'BV', name: 'Bouvet Island'},
  { symbol: 'BR', name: 'Brazil'},
  { symbol: 'IO', name: 'British Indian Ocean Territory'},
  { symbol: 'BN', name: 'Brunei Darussalam'},
  { symbol: 'BG', name: 'Bulgaria'},
  { symbol: 'BF', name: 'Burkina Faso'},
  { symbol: 'BI', name: 'Burundi'},
  { symbol: 'KH', name: 'Cambodia'},
  { symbol: 'CM', name: 'Cameroon'},
  { symbol: 'CA', name: 'Canada'},
  { symbol: 'CV', name: 'Cape Verde'},
  { symbol: 'KY', name: 'Cayman Islands'},
  { symbol: 'CF', name: 'Central African Republic'},
  { symbol: 'TD', name: 'Chad'},
  { symbol: 'CL', name: 'Chile'},
  { symbol: 'CN', name: 'China'},
  { symbol: 'CX', name: 'Christmas Island'},
  { symbol: 'CC', name: 'Cocos Islands'},
  { symbol: 'CO', name: 'Colombia'},
  { symbol: 'KM', name: 'Comoros'},
  { symbol: 'CG', name: 'Congo'},
  { symbol: 'CD', name: 'Congo'},
  { symbol: 'CK', name: 'Cook Islands'},
  { symbol: 'CR', name: 'Costa Rica'},
  { symbol: 'CI', name: 'Côte d\'Ivoire'},
  { symbol: 'HR', name: 'Croatia'},
  { symbol: 'CU', name: 'Cuba'},
  { symbol: 'CW', name: 'Curaçao'},
  { symbol: 'CY', name: 'Cyprus'},
  { symbol: 'CZ', name: 'Czech Republic'},
  { symbol: 'DK', name: 'Denmark'},
  { symbol: 'DJ', name: 'Djibouti'},
  { symbol: 'DM', name: 'Dominica'},
  { symbol: 'DO', name: 'Dominican Republic'},
  { symbol: 'EC', name: 'Ecuador'},
  { symbol: 'EG', name: 'Egypt'},
  { symbol: 'SV', name: 'El Salvador'},
  { symbol: 'GQ', name: 'Equatorial Guinea'},
  { symbol: 'ER', name: 'Eritrea'},
  { symbol: 'EE', name: 'Estonia'},
  { symbol: 'ET', name: 'Ethiopia'},
  { symbol: 'FK', name: 'Falkland Islands'},
  { symbol: 'FO', name: 'Faroe Islands'},
  { symbol: 'FJ', name: 'Fiji'},
  { symbol: 'FI', name: 'Finland'},
  { symbol: 'FR', name: 'France'},
  { symbol: 'GF', name: 'French Guiana'},
  { symbol: 'PF', name: 'French Polynesia'},
  { symbol: 'GA', name: 'Gabon'},
  { symbol: 'GM', name: 'Gambia'},
  { symbol: 'GE', name: 'Georgia'},
  { symbol: 'DE', name: 'Germany'},
  { symbol: 'GH', name: 'Ghana'},
  { symbol: 'GI', name: 'Gibraltar'},
  { symbol: 'GR', name: 'Greece'},
  { symbol: 'GL', name: 'Greenland'},
  { symbol: 'GD', name: 'Grenada'},
  { symbol: 'GP', name: 'Guadeloupe'},
  { symbol: 'GU', name: 'Guam'},
  { symbol: 'GT', name: 'Guatemala'},
  { symbol: 'GG', name: 'Guernsey'},
  { symbol: 'GN', name: 'Guinea'},
  { symbol: 'GW', name: 'Guinea-Bissau'},
  { symbol: 'GY', name: 'Guyana'},
  { symbol: 'HT', name: 'Haiti'},
  { symbol: 'HN', name: 'Honduras'},
  { symbol: 'HK', name: 'Hong Kong'},
  { symbol: 'HU', name: 'Hungary'},
  { symbol: 'IS', name: 'Iceland'},
  { symbol: 'IN', name: 'India'},
  { symbol: 'ID', name: 'Indonesia'},
  { symbol: 'IQ', name: 'Iraq'},
  { symbol: 'IE', name: 'Ireland'},
  { symbol: 'IM', name: 'Isle of Man'},
  { symbol: 'IL', name: 'Israel'},
  { symbol: 'IT', name: 'Italy'},
  { symbol: 'JM', name: 'Jamaica'},
  { symbol: 'JP', name: 'Japan'},
  { symbol: 'JE', name: 'Jersey'},
  { symbol: 'JO', name: 'Jordan'},
  { symbol: 'KZ', name: 'Kazakhstan'},
  { symbol: 'KE', name: 'Kenya'},
  { symbol: 'KI', name: 'Kiribati'},
  { symbol: 'KR', name: 'Korea'},
  { symbol: 'KW', name: 'Kuwait'},
  { symbol: 'KG', name: 'Kyrgyzstan'},
  { symbol: 'LV', name: 'Latvia'},
  { symbol: 'LB', name: 'Lebanon'},
  { symbol: 'LS', name: 'Lesotho'},
  { symbol: 'LR', name: 'Liberia'},
  { symbol: 'LY', name: 'Libya'},
  { symbol: 'LI', name: 'Liechtenstein'},
  { symbol: 'LT', name: 'Lithuania'},
  { symbol: 'LU', name: 'Luxembourg'},
  { symbol: 'MO', name: 'Macao'},
  { symbol: 'MK', name: 'Macedonia'},
  { symbol: 'MG', name: 'Madagascar'},
  { symbol: 'MW', name: 'Malawi'},
  { symbol: 'MY', name: 'Malaysia'},
  { symbol: 'MV', name: 'Maldives'},
  { symbol: 'ML', name: 'Mali'},
  { symbol: 'MT', name: 'Malta'},
  { symbol: 'MQ', name: 'Martinique'},
  { symbol: 'MR', name: 'Mauritania'},
  { symbol: 'MU', name: 'Mauritius'},
  { symbol: 'YT', name: 'Mayotte'},
  { symbol: 'MX', name: 'Mexico'},
  { symbol: 'MD', name: 'Moldova'},
  { symbol: 'MC', name: 'Monaco'},
  { symbol: 'MN', name: 'Mongolia'},
  { symbol: 'ME', name: 'Montenegro'},
  { symbol: 'MS', name: 'Montserrat'},
  { symbol: 'MA', name: 'Morocco'},
  { symbol: 'MZ', name: 'Mozambique'},
  { symbol: 'MM', name: 'Myanmar'},
  { symbol: 'NA', name: 'Namibia'},
  { symbol: 'NR', name: 'Nauru'},
  { symbol: 'NP', name: 'Nepal'},
  { symbol: 'NL', name: 'Netherlands'},
  { symbol: 'NC', name: 'New Caledonia'},
  { symbol: 'NZ', name: 'New Zealand'},
  { symbol: 'NI', name: 'Nicaragua'},
  { symbol: 'NE', name: 'Niger'},
  { symbol: 'NG', name: 'Nigeria'},
  { symbol: 'NU', name: 'Niue'},
  { symbol: 'NF', name: 'Norfolk Island'},
  { symbol: 'MP', name: 'Northern Mariana Islands'},
  { symbol: 'NO', name: 'Norway'},
  { symbol: 'OM', name: 'Oman'},
  { symbol: 'PK', name: 'Pakistan'},
  { symbol: 'PW', name: 'Palau'},
  { symbol: 'PS', name: 'Palestinian Territory'},
  { symbol: 'PA', name: 'Panama'},
  { symbol: 'PG', name: 'Papua New Guinea'},
  { symbol: 'PY', name: 'Paraguay'},
  { symbol: 'PE', name: 'Peru'},
  { symbol: 'PH', name: 'Philippines'},
  { symbol: 'PN', name: 'Pitcairn'},
  { symbol: 'PL', name: 'Poland'},
  { symbol: 'PT', name: 'Portugal'},
  { symbol: 'PR', name: 'Puerto Rico'},
  { symbol: 'QA', name: 'Qatar'},
  { symbol: 'RE', name: 'Réunion'},
  { symbol: 'RO', name: 'Romania'},
  { symbol: 'RU', name: 'Russian Federation'},
  { symbol: 'RW', name: 'Rwanda'},
  { symbol: 'BL', name: 'Saint Barthélemy'},
  { symbol: 'SH', name: 'Saint Helena'},
  { symbol: 'KN', name: 'Saint Kitts and Nevis'},
  { symbol: 'LC', name: 'Saint Lucia'},
  { symbol: 'MF', name: 'Saint Martin'},
  { symbol: 'PM', name: 'Saint Pierre and Miquelon'},
  { symbol: 'VC', name: 'Saint Vincent and the Grenadines'},
  { symbol: 'WS', name: 'Samoa'},
  { symbol: 'SM', name: 'San Marino'},
  { symbol: 'ST', name: 'Sao Tome and Principe'},
  { symbol: 'SA', name: 'Saudi Arabia'},
  { symbol: 'SN', name: 'Senegal'},
  { symbol: 'RS', name: 'Serbia'},
  { symbol: 'SC', name: 'Seychelles'},
  { symbol: 'SL', name: 'Sierra Leone'},
  { symbol: 'SG', name: 'Singapore'},
  { symbol: 'SX', name: 'Sint Maarten'},
  { symbol: 'SK', name: 'Slovakia'},
  { symbol: 'SI', name: 'Slovenia'},
  { symbol: 'SB', name: 'Solomon Islands'},
  { symbol: 'SO', name: 'Somalia'},
  { symbol: 'ZA', name: 'South Africa'},
  { symbol: 'GS', name: 'South Georgia'},
  { symbol: 'SS', name: 'South Sudan'},
  { symbol: 'ES', name: 'Spain'},
  { symbol: 'LK', name: 'Sri Lanka'},
  { symbol: 'SD', name: 'Sudan'},
  { symbol: 'SR', name: 'Suriname'},
  { symbol: 'SJ', name: 'Svalbard and Jan Mayen'},
  { symbol: 'SZ', name: 'Swaziland'},
  { symbol: 'SE', name: 'Sweden'},
  { symbol: 'CH', name: 'Switzerland'},
  { symbol: 'SY', name: 'Syrian Arab Republic'},
  { symbol: 'TW', name: 'Taiwan'},
  { symbol: 'TJ', name: 'Tajikistan'},
  { symbol: 'TZ', name: 'Tanzania'},
  { symbol: 'TH', name: 'Thailand'},
  { symbol: 'TL', name: 'Timor-Leste'},
  { symbol: 'TG', name: 'Togo'},
  { symbol: 'TK', name: 'Tokelau'},
  { symbol: 'TO', name: 'Tonga'},
  { symbol: 'TT', name: 'Trinidad and Tobago'},
  { symbol: 'TN', name: 'Tunisia'},
  { symbol: 'TR', name: 'Turkey'},
  { symbol: 'TM', name: 'Turkmenistan'},
  { symbol: 'TC', name: 'Turks and Caicos Islands'},
  { symbol: 'TV', name: 'Tuvalu'},
  { symbol: 'UG', name: 'Uganda'},
  { symbol: 'UA', name: 'Ukraine'},
  { symbol: 'AE', name: 'United Arab Emirates'},
  { symbol: 'GB', name: 'United Kingdom'},
  { symbol: 'US', name: 'United States'},
  { symbol: 'UY', name: 'Uruguay'},
  { symbol: 'UZ', name: 'Uzbekistan'},
  { symbol: 'VU', name: 'Vanuatu'},
  { symbol: 'VE', name: 'Venezuela'},
  { symbol: 'VN', name: 'Viet Nam'},
  { symbol: 'VG', name: 'Virgin Islands, British'},
  { symbol: 'VI', name: 'Virgin Islands, U.S.'},
  { symbol: 'WF', name: 'Wallis and Futuna'},
  { symbol: 'EH', name: 'Western Sahara'},
  { symbol: 'YE', name: 'Yemen'},
  { symbol: 'ZM', name: 'Zambia'},
  { symbol: 'ZW', name: 'Zimbabwe'}
]